import { Constants } from 'expo';

export const STATUS_BAR_HEIGHT = Constants.statusBarHeight;

export const FB_LOGGED_IN = 'FB_LOGGED_IN'

// registration form constants
export const SET_VOLUNTEER_VILLAGE = 'SET_VOLUNTEER_VILLAGE'
export const SET_VOLUNTEER_DISTRICT = 'SET_VOLUNTEER_DISTRICT'
export const SET_VOLUNTEER_DAPIL = 'SET_VOLUNTEER_DAPIL'
export const SET_VOLUNTEER_NAME = 'SET_VOLUNTEER_NAME'
export const SET_VOLUNTEER_DOB = 'SET_VOLUNTEER_DOB'
export const SET_VOLUNTEER_ADDRESS = 'SET_VOLUNTEER_ADDRESS'
export const SET_VOLUNTEER_NO_KTP = 'SET_VOLUNTEER_NO_KTP'
export const SET_VOLUNTEER_NO_HP = 'SET_VOLUNTEER_NO_HP'
export const SET_VOLUNTEER_NO_WA = 'SET_VOLUNTEER_NO_WA'
export const SET_VOLUNTEER_PHOTO = 'SET_VOLUNTEER_PHOTO'
export const SET_VOLUNTEER_PHOTO_KTP = 'SET_VOLUNTEER_PHOTO_KTP'
